# Generated by Django 3.2.6 on 2021-09-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0002_remove_post_file'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postcomment',
            table='post_comment',
        ),
    ]
