# Generated by Django 3.2.6 on 2021-09-02 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0003_alter_postcomment_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='postcomment',
            table='community_post_comment',
        ),
    ]
