# Generated by Django 3.2.6 on 2021-10-30 10:19

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_no', models.SmallIntegerField(editable=False, verbose_name='회차 번호')),
                ('draw_date', models.DateField(unique=True, verbose_name='추첨 날짜')),
                ('bonus_num', models.SmallIntegerField(editable=False, verbose_name='보너스 당첨 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('size', models.CharField(max_length=100, verbose_name='사이즈')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('serial', models.CharField(max_length=100, verbose_name='시리얼 번호')),
                ('color', models.CharField(max_length=100, verbose_name='색상')),
                ('release_date', models.DateField(verbose_name='릴리즈 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date_time', models.DateTimeField(verbose_name='응모 시작 날짜')),
                ('end_date_time', models.DateTimeField(verbose_name='응모 종료 날짜')),
                ('announce_date_time', models.DateTimeField(blank=True, editable=False, verbose_name='당첨 발표 날짜')),
                ('target_quantity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=3)], verbose_name='목표 티켓 수량')),
                ('progress', models.CharField(blank=True, choices=[('waiting', '응모 대기'), ('ongoing', '응모 진행중'), ('done', '응모 종료'), ('failed', '응모 실패')], editable=False, max_length=10, verbose_name='진행 상황')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='loffle.product', verbose_name='연결된 제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL, verbose_name='등록한 사람')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='loffle.raffle', verbose_name='응모한 래플')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_raffles', to=settings.AUTH_USER_MODEL, verbose_name='응모한 사람')),
            ],
            options={
                'db_table': 'loffle_raffle_apply',
            },
        ),
        migrations.CreateModel(
            name='RaffleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('given_numbers', models.CharField(max_length=100, verbose_name='부여받은 번호')),
                ('raffle_apply', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='candidate', to='loffle.raffleapply', verbose_name='1차 당첨')),
            ],
            options={
                'db_table': 'loffle_raffle_candidate',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.PositiveBigIntegerField(verbose_name='가격')),
            ],
        ),
        migrations.CreateModel(
            name='TicketBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buy_tickets', to='loffle.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loffle_ticket_buy',
            },
        ),
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='winner', to='loffle.rafflecandidate', verbose_name='최종 당첨')),
            ],
            options={
                'db_table': 'loffle_raffle_winner',
            },
        ),
    ]
