# Generated by Django 3.2.6 on 2021-10-06 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('size', models.CharField(max_length=100, verbose_name='사이즈')),
                ('brand', models.CharField(max_length=100, verbose_name='브랜드')),
                ('serial', models.CharField(max_length=100, verbose_name='시리얼 번호')),
                ('color', models.CharField(max_length=100, verbose_name='색상')),
                ('release_date', models.DateField(verbose_name='릴리즈 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Raffle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('begin_at', models.DateTimeField(verbose_name='응모 시작 날짜')),
                ('finish_at', models.DateTimeField(verbose_name='응모 종료 날짜')),
                ('target_quantity', models.PositiveIntegerField(verbose_name='목표 티켓 수량')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to='loffle.product', verbose_name='연결된 제품')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raffles', to=settings.AUTH_USER_MODEL, verbose_name='등록한 사람')),
            ],
        ),
        migrations.CreateModel(
            name='RaffleCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='loffle.raffle', verbose_name='래플')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidate_raffles', to=settings.AUTH_USER_MODEL, verbose_name='1차 당첨자')),
            ],
            options={
                'db_table': 'loffle_raffle_candidate',
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='수량')),
                ('price', models.PositiveBigIntegerField(verbose_name='가격')),
                ('buy', models.ManyToManyField(related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RaffleWinner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raffle_candidate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loffle.rafflecandidate', verbose_name='최종 당첨자')),
            ],
            options={
                'db_table': 'loffle_raffle_winner',
            },
        ),
    ]
