# Generated by Django 3.2.6 on 2021-10-30 11:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rafflecandidate',
            name='raffle_apply',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loffle.raffleapply', verbose_name='1차 당첨'),
        ),
        migrations.AlterField(
            model_name='rafflewinner',
            name='raffle_candidate',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='loffle.rafflecandidate', verbose_name='최종 당첨'),
        ),
    ]
