# Generated by Django 3.2.6 on 2021-10-06 23:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loffle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='buy',
        ),
        migrations.CreateModel(
            name='TicketBuy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='buy_tickets', to='loffle.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'loffle_ticket_buy',
            },
        ),
    ]
