# Generated by Django 3.2.6 on 2021-10-11 09:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loffle', '0002_auto_20211007_0857'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaffleApply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(default=False, editable=False)),
                ('raffle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied', to='loffle.raffle', verbose_name='응모한 래플')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_raffles', to=settings.AUTH_USER_MODEL, verbose_name='응모한 사람')),
            ],
            options={
                'db_table': 'loffle_raffle_apply',
            },
        ),
    ]
