# Generated by Django 3.2.6 on 2021-10-18 11:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0004_auto_20211018_1656'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='announce_date_time',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='당첨 발표 날짜'),
            preserve_default=False,
        ),
    ]
