# Generated by Django 3.2.6 on 2021-10-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0005_raffle_announce_date_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='raffle',
            name='progress',
            field=models.CharField(blank=True, choices=[('waiting', '응모 대기'), ('ongoing', '응모 진행중'), ('done', '응모 종료'), ('failed', '응모 실패')], editable=False, max_length=10, verbose_name='진행 상황'),
        ),
    ]
