# Generated by Django 3.2.6 on 2021-10-21 04:35

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0006_raffle_progress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='raffle',
            name='target_quantity',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(limit_value=3)], verbose_name='목표 티켓 수량'),
        ),
    ]
