# Generated by Django 3.2.6 on 2021-10-22 09:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0007_alter_raffle_target_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='rafflecandidate',
            name='given_numbers',
            field=models.CharField(default=datetime.datetime(2021, 10, 22, 9, 49, 36, 229371, tzinfo=utc), max_length=100, verbose_name='부여받은 번호'),
            preserve_default=False,
        ),
    ]
