# Generated by Django 3.2.6 on 2021-10-25 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loffle', '0008_rafflecandidate_given_numbers'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lotto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draw_no', models.SmallIntegerField(editable=False, verbose_name='회차 번호')),
                ('draw_date', models.DateField(unique=True, verbose_name='추첨 날짜')),
                ('bonus_num', models.SmallIntegerField(editable=False, verbose_name='보너스 당첨 번호')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
